[build]
  # Dossier de build (après npm run build)
  publish = "dist"
  
  # Commande de build
  command = "npm run build"

# Redirections pour le SPA React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers spécifiques pour les formulaires
[[headers]]
  for = "/contact"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"

# Configuration des formulaires
[forms]
  # Protection anti-spam
  honeypot = "bot-field"
  
  # Limite de soumissions (optionnel)
  # submissions_limit = 100

# Variables d'environnement
[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  REACT_APP_ENV = "preview"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  REACT_APP_ENV = "branch"

# Configuration des fonctions (optionnel)
# [functions]
#   directory = "netlify/functions"

# Configuration des plugins (optionnel)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"

# Configuration des notifications de formulaire (optionnel)
# [[plugins]]
#   package = "@netlify/plugin-forms"

# Optimisations de performance
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Compression gzip
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "gzip" 